CREATE TABLE IF NOT EXISTS country (
    id INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    code VARCHAR(20) NOT NULL,
    code_alpha_2 VARCHAR(2) NOT NULL,
    code_alpha_3 VARCHAR(3) NOT NULL,
    flag VARCHAR(255) NULL,
    CONSTRAINT country_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS neighbours (
    id INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    country_id INT8 NOT NULL,
    neighbour_id INT8 NOT NULL,
    CONSTRAINT fk_country FOREIGN KEY (country_id) REFERENCES country(id),
    CONSTRAINT fk_neighbour FOREIGN KEY (neighbour_id) REFERENCES country(id),
    CONSTRAINT chk_equality CHECK (country_id <> neighbour_id),
    CONSTRAINT unq_pair UNIQUE (country_id, neighbour_id)
);
