name: Build target version docker image
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Target version for build operation'
        required: true
        default: 'latest'
env:
  DOCKER_REGISTRY: ghcr.io
  IMAGE_NAME: notch-bootcamp/country-app-node
jobs:
  pipeline:
    name: Build and Publish docker image
    runs-on: dev-crawl
    environment: production
    steps:
      - uses: actions/checkout@v4
      - name: Set up version
        run: |
          VERSION="${{ github.event.inputs.version }}"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
      - name: Log into Docker registry
        run: |-
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: Build Docker image
        run: |-
          docker build -t $DOCKER_REGISTRY/$IMAGE_NAME:$VERSION --build-arg port=3003 .
      - name: Push Docker image
        run: |-
          docker push $DOCKER_REGISTRY/$IMAGE_NAME:$VERSION
